### ISSUE TITLE
Does not work with Typescript 3.4

### ISSUE THREAD

**Issue by jackmellis** [joshburgess/redux-most#34]
We've just updated to the latest TS version and now our build fails with the following error:

```
node_modules/redux-most/index.d.ts:27:32 - error TS2344: Type 'Dispatch<A>' does not satisfy the constraint 'Dispatch<AnyAction>'.
  Type 'AnyAction' is not assignable to type 'A'.

27   middlewareApi: MiddlewareAPI<Dispatch<A>, S>,
```

I downgraded TS to the last non-3.4 version (I think it was 3.3.4000) and it worked fine. Presumably TS is now picking up on something that was missed before...
